### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by JetForMe** [esphen/wsta#28]
I tried installing `wsta` on my M1 MacBook Pro. Dunno if Rust has changed since it was last updated, but I got an error compiling:

```
==> Installing esphen/wsta/wsta
==> cargo build --release
Last 15 lines from /Users/rmann/Library/Logs/Homebrew/wsta/01.cargo:
error[E0713]: borrow may still be in use when destructor runs
   --> /Users/rmann/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/url-1.2.4/src/form_urlencoded.rs:246:40
    |
244 | impl<'a> Target for ::UrlQuery<'a> {
    |      -- lifetime `'a` defined here
245 |     fn as_mut_string(&mut self) -> &mut String { &mut self.url.serialization }
246 |     fn finish(self) -> &'a mut ::Url { self.url }
    |                                        ^^^^^^^^ - here, drop of `self` needs exclusive access to `*self.url`, because the type `UrlQuery<'_>` implements the `Drop` trait
    |                                        |
    |                                        returning this value requires that `*self.url` is borrowed for `'a`

For more information about this error, try `rustc --explain E0713`.
error: could not compile `url` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
  esphen/wsta

/opt/homebrew/Library/Homebrew/utils/github/api.rb:304:in `raise_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::API::ValidationFailedError)
	from /opt/homebrew/Library/Homebrew/utils/github/api.rb:234:in `open_rest'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:166:in `search'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:34:in `search_issues'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:67:in `issues_for_formula'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:491:in `fetch_issues'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:487:in `issues'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:541:in `dump'
	from /opt/homebrew/Library/Homebrew/brew.rb:155:in `rescue in <main>'
	from /opt/homebrew/Library/Homebrew/brew.rb:143:in `<main>'
/opt/homebrew/Library/Homebrew/formula.rb:2307:in `block in system': Failed executing: cargo build --release (BuildError)
	from /opt/homebrew/Library/Homebrew/formula.rb:2243:in `open'
	from /opt/homebrew/Library/Homebrew/formula.rb:2243:in `system'
	from /opt/homebrew/Library/Taps/esphen/homebrew-wsta/HomebrewFormula/wsta.rb:12:in `install'
	from /opt/homebrew/Library/Homebrew/build.rb:172:in `block (3 levels) in install'
	from /opt/homebrew/Library/Homebrew/utils.rb:588:in `with_env'
	from /opt/homebrew/Library/Homebrew/build.rb:134:in `block (2 levels) in install'
	from /opt/homebrew/Library/Homebrew/formula.rb:1297:in `block in brew'
	from /opt/homebrew/Library/Homebrew/formula.rb:2473:in `block (2 levels) in stage'
	from /opt/homebrew/Library/Homebrew/utils.rb:588:in `with_env'
	from /opt/homebrew/Library/Homebrew/formula.rb:2472:in `block in stage'
	from /opt/homebrew/Library/Homebrew/resource.rb:126:in `block (2 levels) in unpack'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	from /opt/homebrew/Library/Homebrew/resource.rb:122:in `block in unpack'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	from /opt/homebrew/Library/Homebrew/resource.rb:208:in `mktemp'
	from /opt/homebrew/Library/Homebrew/resource.rb:121:in `unpack'
	from /opt/homebrew/Library/Homebrew/resource.rb:96:in `stage'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	from /opt/homebrew/Library/Homebrew/formula.rb:2452:in `stage'
	from /opt/homebrew/Library/Homebrew/formula.rb:1290:in `brew'
	from /opt/homebrew/Library/Homebrew/build.rb:129:in `block in install'
	from /opt/homebrew/Library/Homebrew/utils.rb:588:in `with_env'
	from /opt/homebrew/Library/Homebrew/build.rb:124:in `install'
	from /opt/homebrew/Library/Homebrew/build.rb:224:in `<main>'
```

**Comment by eliihen** [comment]
Yeah, rust has changed a lot in the mean time. I did a ground-up rewrite of wsta at some point which resulted in https://github.com/getwurl/wurl which was architechturally superior and should be more performant. You can try that and see if that works for you. It's been a little while since I tried it.

**Comment by JetForMe** [comment]
I found websocat, which is working well enough for me, but if you want to add [brew](https://brew.sh) support for wurl, I'd love to give it a try!
